default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres_password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: board_meeting_development

test:
  <<: *default
  database: board_meeting_test
